### ISSUE TITLE
安装问题

### ISSUE THREAD

**Issue by soul0000dream** [hanhuoer/Jusic-serve#2]
音乐服务配置好之后
springboot后端启动报错:音乐获取异常, 请检查音乐服务; UnirestException: [java.net.UnknownHostException: domain]是什么原因呀

**Comment by hanhuoer** [comment]
请检查一下配置是否正确：
> /resources/*.yml
```yaml
jusic:
  music-serve-domain: 'http://host:port'
```

**Comment by soul0000dream** [comment]
谢谢，我改成这样可以了
music-serve-domain: 'http://127.0.0.1:8888'

**Comment by hanhuoer** [comment]
好的，注意[音乐服务](https://github.com/hanhuoer/Musicoo)要保证是可用的，不然应用没法正常工作。
另外，这里已经很久没更新了，但后来有人基于本项目扩展了些功能，具体你可以参考一下 https://github.com/JumpAlang/Jusic-serve

**Comment by soul0000dream** [comment]
好的，谢谢您

**Comment by soul0000dream** [comment]
这个音乐服务好像是网易API，我把音乐服务下载到本地，应该不会停的吧，大佬

**Comment by hanhuoer** [comment]
是的，Musicoo 是提供了网易云音乐的基础服务，例如获取音乐外链、音乐详情、歌单列表等等，正是这些功能支撑起了 Jusic 的正常运行。
Musicoo 对外提供了 HTTP 的接口，所以你只需要把项目 clone 后运行起来，最后把服务的地址端口完整地配置到 Jusic 里面就好了。

Musicoo 的接口可以参考 https://github.com/hanhuoer/Musicoo/wiki
